#!/usr/bin/env bash
# Regenerate the pywal palette from the newly selected wallpaper, and push it to
# the consumers that cannot notice the change by themselves.
#
# Wired in via ~/.config/waypaper/config.ini:
#     post_command = /home/markoruzic997/.config/waypaper/wallpaper_update.sh "$wallpaper"
#
# A literal path, not ~ or $HOME: this is copied verbatim into config.ini and
# waypaper is not guaranteed to run it through a shell.
#
# waypaper substitutes $wallpaper with the image it just applied.
#
# Who needs pushing and who does not:
#
#   Quickshell bar  no  -- Theme.qml watches ~/.cache/wal/colors.json and
#                          recolours live, with no restart and no signal.
#   rofi            no  -- reads the rendered .rasi files on each launch.
#   Hyprland        YES -- `source`s a generated file, and only re-reads its
#                          config on an explicit reload.
#   Ptyxis          YES -- reads palettes from a data dir, not from the cache.
#   eww             YES -- compiles its scss at config load. Only relevant on
#                          the sway machine; guarded so it is a no-op here.

set -uo pipefail

WAL="$HOME/.local/bin/wal"
CACHE="$HOME/.cache/wal"
COLORS="$CACHE/colors.scss"
PTYXIS_PALETTES="$HOME/.local/share/org.gnome.Ptyxis/palettes"

img="${1:-}"
[ -n "$img" ] || { echo "wallpaper_update: no image argument" >&2; exit 1; }
[ -f "$img" ] || { echo "wallpaper_update: no such image: $img" >&2; exit 1; }
img="$(realpath "$img")"

# waypaper can fire the hook more than once for a single change (once per
# monitor with `monitors = All`). Without this, several `wal` runs race on
# ~/.cache/wal and the consumers below get reloaded repeatedly.
exec 9>"${XDG_RUNTIME_DIR:-/tmp}/wallpaper_update.lock"
flock -n 9 || exit 0

# pywal records the source image in colors.scss; if it already matches, the
# palette is current and reloading would only cause a needless flicker.
current="$(sed -n 's/^\$wallpaper: "\(.*\)";$/\1/p' "$COLORS" 2>/dev/null)"
if [ "$current" = "$img" ]; then
    exit 0
fi

# -n: do not set the wallpaper, waypaper's backend already did that
# -q: quiet
# -e: do NOT reload gtk/xrdb/i3/sway/polybar. Without this pywal runs
#     `swaymsg reload`, which re-applies `output * bg #222222 solid_color` and
#     re-runs `exec_always waypaper --restore` -- leaving a second swaybg
#     stacked over the real wallpaper, and re-entering this very hook.
if ! "$WAL" -i "$img" -n -q -e; then
    echo "wallpaper_update: wal failed on $img" >&2
    exit 1
fi

# ---------------------------------------------------------------- Hyprland
#
# Generated here rather than as a pywal template because the accent has to be
# *chosen*, not read: pywal frequently returns six muddy near-greys, so
# Theme.qml scores color1-6 on saturation weighted by brightness and takes the
# liveliest. The window borders have to use the same answer as the bar, or the
# desktop accents itself two different colours -- so the scoring is duplicated
# here. Keep the formula in step with Theme.qml's `accentRaw`.
if python3 - "$CACHE" <<'PY'
import colorsys, json, pathlib, sys

cache = pathlib.Path(sys.argv[1])
data = json.loads((cache / "colors.json").read_text())
colors, special = data["colors"], data["special"]


def rgb(hex_colour):
    return tuple(int(hex_colour[i:i + 2], 16) / 255 for i in (1, 3, 5))


def to_hex(r, g, b):
    return "{:02x}{:02x}{:02x}".format(*(round(c * 255) for c in (r, g, b)))


# Theme.qml, `accentRaw`: pywal often returns six muddy near-greys, so pick the
# liveliest by saturation weighted by brightness rather than trusting color4.
def liveliness(hex_colour):
    _, saturation, value = colorsys.rgb_to_hsv(*rgb(hex_colour))
    return saturation * (0.4 + value)


ramp = [colors["color%d" % n] for n in range(1, 7)]
raw = max(ramp, key=liveliness)

# Theme.qml, `accent`, dark branch: force the pick bright enough to read on
# near-black. Without this floor a greyscale wallpaper yields something like
# #444444 -- which the bar lifts to #c7c7c7 while the window borders would stay
# nearly invisible. Deliberately the dark branch: the bar can toggle light mode
# at runtime, a compositor border cannot follow, and dark is the default.
hue, saturation, value = colorsys.rgb_to_hsv(*rgb(raw))
accent = to_hex(*colorsys.hsv_to_rgb(
    hue,
    min(1.0, saturation * 1.15),
    max(0.78, value),
))

(cache / "colors-hyprland.conf").write_text(
    "# Generated by waypaper/wallpaper_update.sh. Do not edit.\n"
    "# Mirrors Theme.qml's dark-mode `accent`; keep the two in step.\n"
    "$wal_accent = rgb(%s)\n" % accent
    + "$wal_dim    = rgb(%s)\n" % colors["color8"].lstrip("#")
    + "$wal_bg     = rgb(%s)\n" % special["background"].lstrip("#")
)
PY
then
    # Only reload a compositor that is actually running; hyprctl against a dead
    # socket prints its own error and would make this look broken on sway.
    if command -v hyprctl >/dev/null 2>&1 && hyprctl version >/dev/null 2>&1; then
        hyprctl reload >/dev/null 2>&1 || echo "wallpaper_update: hyprctl reload failed" >&2
    fi
else
    echo "wallpaper_update: could not generate colors-hyprland.conf" >&2
fi

# ------------------------------------------------------------------ Ptyxis
#
# Copied out of the cache rather than symlinked from the repo: see the header of
# wal/.config/wal/templates/colors-ptyxis.palette. Open windows keep the palette
# they started with; new tabs pick this one up.
if [ -f "$CACHE/colors-ptyxis.palette" ]; then
    mkdir -p "$PTYXIS_PALETTES"
    cp -f "$CACHE/colors-ptyxis.palette" "$PTYXIS_PALETTES/pywal.palette" \
        || echo "wallpaper_update: could not install the Ptyxis palette" >&2
fi

# --------------------------------------------------------------------- eww
#
# The sway machine's bar. eww compiles its scss (and with it
# ~/.cache/wal/colors.scss) at config load, so new colours only appear after a
# reload. Guarded on the daemon answering, so this is a silent no-op on a
# Hyprland session where eww is not running at all -- and deliberately no longer
# starts the bar, which was correct when eww was the only bar and is not now.
if command -v eww >/dev/null 2>&1 && eww ping >/dev/null 2>&1; then
    eww reload
fi
